### ISSUE TITLE
上传数据

### ISSUE THREAD

**Issue by daxinnan** [miketwes/XX-Net-Linux#6]
可以麻烦有时间再上传一下之前误会删除的GotoX下的内容吗，我不小心删除了(;´༎ຶД༎ຶ`)
那些data数据是用什么扫描出来的可用ip吗

**Comment by miketwes** [comment]
https://github.com/miketwes/GotoX-data

data数据是GotoX在运行过程中扫描维护的

**Comment by daxinnan** [comment]
> https://github.com/miketwes/GotoX-data
> 
> data数据是GotoX在运行过程中扫描维护的

原来是这样，可以麻烦有时间上传下吗

**Comment by daxinnan** [comment]
> 可以
谢谢了
